version: '3.3'
services:
  api-gateway2:
    image: nginx:stable
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./web/html:/usr/share/nginx/html
    ports:
      - 82:82
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  nginx-streamlit-3:
    build:
      context: .
      dockerfile: Dockerfile.app3
    image: nginx-streamlit-3
    ports:
      - '8890:8890'
    expose:
      - '8890'

networks:
  default:
    name: duck-test-network
