version: '3.3'
services:
  nginx-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-streamlit
    ports:
      - '8888:8888'
    expose:
      - '8888'

networks:
  default:
    name: exp-network
