version: '3.3'
services:
  nginx-streamlit-1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    image: nginx-streamlit-1
    ports:
      - '8888:8888'
    expose:
      - '8888'

  nginx-streamlit-2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    image: nginx-streamlit-2
    ports:
      - '8889:8889'
    expose:
      - '8889'

networks:
  default:
    name: duck-test-network
